version: "3.8"

services:
  app:
    build: .
    container_name: app_service
    restart: unless-stopped
    depends_on:
      - redis
    networks: [holded_celig_network]
    ports:
      - "8080:8000"                # host:container
    environment:
      BASIC_AUTH_USER: luis
      BASIC_AUTH_PASS: 12345
      # cualquier otra variable que uses
    volumes:
      - ./src/config/credentials.json:/app/src/config/credentials.json:rw  # persiste cambios
    command: >
      hypercorn src.quart_app.app:app --bind 0.0.0.0:8000 --worker-class asyncio
  redis:
    image: redis:latest
    container_name: redis_service
    restart: unless-stopped
    networks: [holded_celig_network]
    command: ["redis-server", "--appendonly", "yes"]  # no host port → no clash

  celery_worker:
    build: .
    container_name: celery_worker
    restart: unless-stopped
    depends_on: [redis]
    networks: [holded_celig_network]
    command: >
      celery -A src.workers.celery_config worker --loglevel=info

  celery_beat:
    build: .
    container_name: celery_beat
    restart: unless-stopped
    depends_on: [redis]
    networks: [holded_celig_network]
    command: >
      celery -A src.workers.celery_config beat --loglevel=info

networks:
  holded_celig_network:
    driver: bridge
