version: '3.8'

services:
  app:
    build: .
    container_name: app_service
    restart: always
    depends_on:
      - redis
      - celery_worker
      - celery_beat
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - redis
    command: celery -A config.celery_config worker --loglevel=info

  celery_beat:
    build: .
    container_name: celery_beat
    restart: always
    depends_on:
      - redis
    command: celery -A config.celery_config beat --loglevel=info
