version: "3.8"

services:
  app:
    build: .
    container_name: app_service
    restart: always
    depends_on:
      - redis
      - celery_worker
      - celery_beat
    networks: [holded_celig_network]
    ports:
      - "8080:8000"        # host-port 8080 now; change if you like
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    # ---- NEW ----
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    # (or any other command that runs your web/API;
    #  but DOES NOT start celery)

  redis:
    image: redis:latest
    container_name: redis_service
    restart: unless-stopped
    networks: [holded_celig_network]
    command: ["redis-server", "--appendonly", "yes"]  # no host port → no clash

  celery_worker:
    build: .
    container_name: celery_worker
    restart: unless-stopped
    depends_on: [redis]
    networks: [holded_celig_network]
    command: >
      celery -A src.workers.celery_config worker --loglevel=info

  celery_beat:
    build: .
    container_name: celery_beat
    restart: unless-stopped
    depends_on: [redis]
    networks: [holded_celig_network]
    command: >
      celery -A src.workers.celery_config beat --loglevel=info

networks:
  holded_celig_network:
    driver: bridge
